# Generated by Django 3.2.6 on 2021-09-11 19:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additionalRepetitions', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)])),
                ('initialRepetitions', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)])),
                ('maximumRepetitions', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(1)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User settings',
            },
        ),
    ]
